// Generated by gencpp from file begginer_tutorials/mesajeTest.msg
// DO NOT EDIT!


#ifndef BEGGINER_TUTORIALS_MESSAGE_MESAJETEST_H
#define BEGGINER_TUTORIALS_MESSAGE_MESAJETEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace begginer_tutorials
{
template <class ContainerAllocator>
struct mesajeTest_
{
  typedef mesajeTest_<ContainerAllocator> Type;

  mesajeTest_()
    : numero(0)  {
    }
  mesajeTest_(const ContainerAllocator& _alloc)
    : numero(0)  {
  (void)_alloc;
    }



   typedef uint32_t _numero_type;
  _numero_type numero;




  typedef boost::shared_ptr< ::begginer_tutorials::mesajeTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::begginer_tutorials::mesajeTest_<ContainerAllocator> const> ConstPtr;

}; // struct mesajeTest_

typedef ::begginer_tutorials::mesajeTest_<std::allocator<void> > mesajeTest;

typedef boost::shared_ptr< ::begginer_tutorials::mesajeTest > mesajeTestPtr;
typedef boost::shared_ptr< ::begginer_tutorials::mesajeTest const> mesajeTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::begginer_tutorials::mesajeTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace begginer_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'begginer_tutorials': ['/home/ericros/catkin_ws/src/begginer_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::begginer_tutorials::mesajeTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::begginer_tutorials::mesajeTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::begginer_tutorials::mesajeTest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b32de927a501baab19ed61de1e6e9fe3";
  }

  static const char* value(const ::begginer_tutorials::mesajeTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb32de927a501baabULL;
  static const uint64_t static_value2 = 0x19ed61de1e6e9fe3ULL;
};

template<class ContainerAllocator>
struct DataType< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "begginer_tutorials/mesajeTest";
  }

  static const char* value(const ::begginer_tutorials::mesajeTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 numero\n\
";
  }

  static const char* value(const ::begginer_tutorials::mesajeTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numero);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mesajeTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::begginer_tutorials::mesajeTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::begginer_tutorials::mesajeTest_<ContainerAllocator>& v)
  {
    s << indent << "numero: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.numero);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGGINER_TUTORIALS_MESSAGE_MESAJETEST_H
