# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from trabajo/usuario.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import trabajo.msg

class usuario(genpy.Message):
  _md5sum = "1ca52202970cc42e97caba153d2caf37"
  _type = "trabajo/usuario"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """inf_personal_usuario infPersonal
string emocion
pos_usuario posicion

================================================================================
MSG: trabajo/inf_personal_usuario
string nombre
uint32 edad
string idiomas

================================================================================
MSG: trabajo/pos_usuario
uint32 x
uint32 y
uint32 z
"""
  __slots__ = ['infPersonal','emocion','posicion']
  _slot_types = ['trabajo/inf_personal_usuario','string','trabajo/pos_usuario']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       infPersonal,emocion,posicion

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(usuario, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.infPersonal is None:
        self.infPersonal = trabajo.msg.inf_personal_usuario()
      if self.emocion is None:
        self.emocion = ''
      if self.posicion is None:
        self.posicion = trabajo.msg.pos_usuario()
    else:
      self.infPersonal = trabajo.msg.inf_personal_usuario()
      self.emocion = ''
      self.posicion = trabajo.msg.pos_usuario()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.infPersonal.nombre
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_I.pack(self.infPersonal.edad))
      _x = self.infPersonal.idiomas
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.emocion
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.posicion.x, _x.posicion.y, _x.posicion.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.infPersonal is None:
        self.infPersonal = trabajo.msg.inf_personal_usuario()
      if self.posicion is None:
        self.posicion = trabajo.msg.pos_usuario()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.infPersonal.nombre = str[start:end].decode('utf-8')
      else:
        self.infPersonal.nombre = str[start:end]
      start = end
      end += 4
      (self.infPersonal.edad,) = _struct_I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.infPersonal.idiomas = str[start:end].decode('utf-8')
      else:
        self.infPersonal.idiomas = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.emocion = str[start:end].decode('utf-8')
      else:
        self.emocion = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.posicion.x, _x.posicion.y, _x.posicion.z,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.infPersonal.nombre
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_I.pack(self.infPersonal.edad))
      _x = self.infPersonal.idiomas
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.emocion
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.posicion.x, _x.posicion.y, _x.posicion.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.infPersonal is None:
        self.infPersonal = trabajo.msg.inf_personal_usuario()
      if self.posicion is None:
        self.posicion = trabajo.msg.pos_usuario()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.infPersonal.nombre = str[start:end].decode('utf-8')
      else:
        self.infPersonal.nombre = str[start:end]
      start = end
      end += 4
      (self.infPersonal.edad,) = _struct_I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.infPersonal.idiomas = str[start:end].decode('utf-8')
      else:
        self.infPersonal.idiomas = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.emocion = str[start:end].decode('utf-8')
      else:
        self.emocion = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.posicion.x, _x.posicion.y, _x.posicion.z,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
