// Generated by gencpp from file begginer_tutorials/tipo_servicio.msg
// DO NOT EDIT!


#ifndef BEGGINER_TUTORIALS_MESSAGE_TIPO_SERVICIO_H
#define BEGGINER_TUTORIALS_MESSAGE_TIPO_SERVICIO_H

#include <ros/service_traits.h>


#include <begginer_tutorials/tipo_servicioRequest.h>
#include <begginer_tutorials/tipo_servicioResponse.h>


namespace begginer_tutorials
{

struct tipo_servicio
{

typedef tipo_servicioRequest Request;
typedef tipo_servicioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct tipo_servicio
} // namespace begginer_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::begginer_tutorials::tipo_servicio > {
  static const char* value()
  {
    return "f15f121d0be77fd6967bf4d5c453888a";
  }

  static const char* value(const ::begginer_tutorials::tipo_servicio&) { return value(); }
};

template<>
struct DataType< ::begginer_tutorials::tipo_servicio > {
  static const char* value()
  {
    return "begginer_tutorials/tipo_servicio";
  }

  static const char* value(const ::begginer_tutorials::tipo_servicio&) { return value(); }
};


// service_traits::MD5Sum< ::begginer_tutorials::tipo_servicioRequest> should match 
// service_traits::MD5Sum< ::begginer_tutorials::tipo_servicio > 
template<>
struct MD5Sum< ::begginer_tutorials::tipo_servicioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::begginer_tutorials::tipo_servicio >::value();
  }
  static const char* value(const ::begginer_tutorials::tipo_servicioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::begginer_tutorials::tipo_servicioRequest> should match 
// service_traits::DataType< ::begginer_tutorials::tipo_servicio > 
template<>
struct DataType< ::begginer_tutorials::tipo_servicioRequest>
{
  static const char* value()
  {
    return DataType< ::begginer_tutorials::tipo_servicio >::value();
  }
  static const char* value(const ::begginer_tutorials::tipo_servicioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::begginer_tutorials::tipo_servicioResponse> should match 
// service_traits::MD5Sum< ::begginer_tutorials::tipo_servicio > 
template<>
struct MD5Sum< ::begginer_tutorials::tipo_servicioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::begginer_tutorials::tipo_servicio >::value();
  }
  static const char* value(const ::begginer_tutorials::tipo_servicioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::begginer_tutorials::tipo_servicioResponse> should match 
// service_traits::DataType< ::begginer_tutorials::tipo_servicio > 
template<>
struct DataType< ::begginer_tutorials::tipo_servicioResponse>
{
  static const char* value()
  {
    return DataType< ::begginer_tutorials::tipo_servicio >::value();
  }
  static const char* value(const ::begginer_tutorials::tipo_servicioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGGINER_TUTORIALS_MESSAGE_TIPO_SERVICIO_H
