// Generated by gencpp from file trabajo/inf_personal_usuario.msg
// DO NOT EDIT!


#ifndef TRABAJO_MESSAGE_INF_PERSONAL_USUARIO_H
#define TRABAJO_MESSAGE_INF_PERSONAL_USUARIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trabajo
{
template <class ContainerAllocator>
struct inf_personal_usuario_
{
  typedef inf_personal_usuario_<ContainerAllocator> Type;

  inf_personal_usuario_()
    : nombre()
    , edad(0)
    , idiomas()  {
    }
  inf_personal_usuario_(const ContainerAllocator& _alloc)
    : nombre(_alloc)
    , edad(0)
    , idiomas(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nombre_type;
  _nombre_type nombre;

   typedef uint32_t _edad_type;
  _edad_type edad;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _idiomas_type;
  _idiomas_type idiomas;




  typedef boost::shared_ptr< ::trabajo::inf_personal_usuario_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trabajo::inf_personal_usuario_<ContainerAllocator> const> ConstPtr;

}; // struct inf_personal_usuario_

typedef ::trabajo::inf_personal_usuario_<std::allocator<void> > inf_personal_usuario;

typedef boost::shared_ptr< ::trabajo::inf_personal_usuario > inf_personal_usuarioPtr;
typedef boost::shared_ptr< ::trabajo::inf_personal_usuario const> inf_personal_usuarioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trabajo::inf_personal_usuario_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trabajo::inf_personal_usuario_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trabajo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'trabajo': ['/home/ericros/catkin_ws/src/trabajo/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trabajo::inf_personal_usuario_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trabajo::inf_personal_usuario_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trabajo::inf_personal_usuario_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb9313db1342398a33edd7dccf789b81";
  }

  static const char* value(const ::trabajo::inf_personal_usuario_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb9313db1342398aULL;
  static const uint64_t static_value2 = 0x33edd7dccf789b81ULL;
};

template<class ContainerAllocator>
struct DataType< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trabajo/inf_personal_usuario";
  }

  static const char* value(const ::trabajo::inf_personal_usuario_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nombre\n\
uint32 edad\n\
string idiomas\n\
";
  }

  static const char* value(const ::trabajo::inf_personal_usuario_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nombre);
      stream.next(m.edad);
      stream.next(m.idiomas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inf_personal_usuario_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trabajo::inf_personal_usuario_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trabajo::inf_personal_usuario_<ContainerAllocator>& v)
  {
    s << indent << "nombre: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nombre);
    s << indent << "edad: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.edad);
    s << indent << "idiomas: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.idiomas);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRABAJO_MESSAGE_INF_PERSONAL_USUARIO_H
